export type RoleKey = 'admin' | 'manager' | 'sales' | 'finance' | 'warehouse' | 'procurement' | 'operations' | 'executive';
export type AuthSession = { email: string; name: string; role: RoleKey; branch: string; branchId?: string | null; token: string; lastLoginAt: string; permissions?: string[]; };
export type SignupPayload = { fullName: string; email: string; roleKey?: RoleKey; branchId?: string | null; };
export type KPI = { label: string; value: string; detail: string };
export type PanelGroup = { title: string; items: string[] };
export type Customer = {
  id: string;
  name: string;
  owner: string;
  branch: string;
  status: string;
  balance: string;
  risk: string;
  creditTerms: string;
  priceList: string;
  contact: string;
  phone: string;
  notes: string;
  nextAction: string;
  activity: string[];
};
export type Supplier = { id: string; name: string; category: string; leadTime: string; status: string; contact: string; nextAction: string; };
export type PurchaseOrder = { id: string; supplier: string; branch: string; status: string; value: string; eta: string; buyer: string; nextAction: string; };
export type Product = { id: string; sku: string; name: string; branch: string; status: string; stock: number; reorderAt: number; price: string; cost: string; supplier: string; barcode: string; variants: string; movementSummary: string; nextAction: string; };
export type QuoteStatus = 'Draft' | 'Pending approval' | 'Approved' | 'Sent to customer' | 'Converted';
export type Quote = { id: string; customer: string; owner: string; value: string; status: string; validity: string; branch: string; trigger: string; updated: string; notes: string; nextAction: string; };
export type QuoteLine = { id: string; sku: string; description: string; qty: number; unitPrice: string; total: string; };
export type QuoteWorkflowEvent = { label: string; detail: string; };
export type ActivityEntry = { id: string; title: string; detail: string; actor: string; timestamp: string; recordType: 'quote' | 'invoice' | 'payment' | 'system' | string; recordId: string; recordPath: string; customerId?: string | null; status?: string; };
export type QuoteDetail = Quote & { customerId?: string; subtotal: string; tax: string; total: string; marginBand: string; approvalOwner: string; sourceCustomerId: string; lines: QuoteLine[]; workflow: QuoteWorkflowEvent[]; activityLog: ActivityEntry[]; };
export type Invoice = { id: string; customerId?: string; customer: string; amount: string; branch: string; status: string; due: string; source: string; paymentStatus: string; tax: string; reminders: string; nextAction: string; };
export type InvoiceDetail = Invoice & { sourceCustomerId: string; sourceQuoteId: string | null; subtotal: string; total: string; issuedOn: string; lines: QuoteLine[]; workflow: QuoteWorkflowEvent[]; activityLog: ActivityEntry[]; };
export type Payment = { id: string; ref: string; customerId: string; party: string; amount: string; method: string; status: string; date: string; appliedTo: string; proof: string; nextAction: string; linkedInvoiceId?: string | null; sourceCustomerId?: string; activityLog?: ActivityEntry[]; };
export type NotificationType = 'approval' | 'collection' | 'payment' | 'stock' | 'general';
export type Notification = { id: string; title: string; meta: string; state: string; read: boolean; type: NotificationType | string; dismissed?: boolean; snoozedUntil?: string | null; };
export type AutomationSettings = { triggerMode: string; closeTime: string; sendToManagers: boolean; sendToExecutives: boolean; managerRecipients: string[]; executiveRecipients: string[]; defaultManagerBranch: string; branchManagers: { branch: string; manager: string; email: string }[]; };
export type Settings = { themes: string[]; paymentModes: string[]; density: string[]; supportEmail: string; whatsapp: string; business: { currency: string; taxDefault: string; paymentTerms: string; defaultBranch: string; }; automation?: AutomationSettings; };
export type Role = { key: RoleKey; label: string; description: string; dashboards: string[]; };
export type TopClient = { customerId: string; name: string; revenue: string; invoices: number; averageOrderValue: string; overdueBalance: string; trend: string; };
export type OperationalActionItem = { id: string; title: string; detail: string; owner: string; branch: string; priority: 'high' | 'medium' | 'low' | string; recordPath: string; actionLabel: string; status: string; };
export type BranchSnapshot = { branch: string; approvals: number; collections: number; exceptions: number };
export type DashboardResponse = { role: string; kpis: KPI[]; panels: PanelGroup[]; highlights: Notification[]; recentCustomers: Customer[]; lowStockProducts: Product[]; topClients: TopClient[]; actionCenter: { branchSnapshots: BranchSnapshot[]; actionQueue: OperationalActionItem[]; auditHighlights: ActivityEntry[]; }; };
export type PurchaseHistoryEntry = { id: string; date: string; type: 'invoice' | 'payment' | 'quote'; reference: string; amount: string; status: string; note: string; };
export type TopProduct = { sku: string; name: string; quantity: number; revenue: string; };
export type CustomerSummary = { customerId: string; totalSpend: string; invoiceCount: number; averageOrderValue: string; overdueBalance: string; lastPurchaseDate: string; lastPaymentDate: string; collectionStatus: string; topProducts: TopProduct[]; openQuotes: Quote[]; recentInvoices: Invoice[]; recentPayments: Payment[]; purchaseHistory: PurchaseHistoryEntry[]; overdueInvoices: number; openBalance: string; accountHealth: string; linkedActivity: ActivityEntry[]; };
export type QuoteConversionResult = { quote: QuoteDetail; invoice: InvoiceDetail; reused: boolean; };
export type EmailTemplateKind = 'quote-send' | 'invoice-reminder' | 'payment-proof';
export type EmailDraft = { kind: EmailTemplateKind; subject: string; to: string; cc?: string; recordId: string; customerName: string; intro: string; body: string[]; closing: string; };
export type ReportBranch = { branchId: string; branch: string; date: string; totalSales: number; target: number; varianceToTarget: number; targetAchievedPct: number; posSales: number; invoiceSales: number; cashSales: number; cardSales: number; eftSales: number; transactions: number; averageBasket: number; };
export type ReportTotals = { totalSales: number; target: number; varianceToTarget: number; targetAchievedPct: number; posSales: number; invoiceSales: number; cashSales: number; cardSales: number; eftSales: number; transactions: number; };
export type SellerRow = { name: string; branch: string; sales: number; target: number };
export type EmailDispatch = { id: string; sentAt: string; recipients: string[]; provider: string; subject: string; status: string; date: string; companyTotal: number; branchCount: number; resend: boolean; closedRecordId?: string | null; };
export type DayCloseRecord = { id: string; closedAt: string; trigger: string; date: string; totalSales: number; varianceToTarget: number; sentStatus: 'pending' | 'sent'; sentAt?: string | null; closedBy: string; emailDispatchId?: string | null; branchSummaries: ReportBranch[]; };
export type CloseStatus = { date: string; state: 'open' | 'closed'; label: string; lastClosedAt: string | null; lastClosedBy: string | null; recordId: string | null; };
export type SendStatus = { state: 'not-ready' | 'pending' | 'sent'; label: string; lastSentAt: string | null; duplicateBlocked: boolean; lastDispatchId: string | null; };
export type AutomationAuditEntry = { id: string; occurredAt: string; actor: string; action: string; status: 'success' | 'blocked' | 'info' | 'error'; detail: string; branch: string; date: string; };
export type BranchCloseHistoryRow = { recordId: string; branch: string; date: string; closedAt: string; totalSales: number; varianceToTarget: number; sentStatus: 'pending' | 'sent'; };
export type ReportsResponse = { scope: string; date: string; canViewAllBranches: boolean; visibleBranches: ReportBranch[]; totals: ReportTotals; sellerBoard: SellerRow[]; emailPreview: { subject: string; body: string }; emailDispatches: EmailDispatch[]; dayCloseHistory: DayCloseRecord[]; branchCloseHistory: BranchCloseHistoryRow[]; automation: AutomationSettings; closeStatus: CloseStatus; sendStatus: SendStatus; auditTrail: AutomationAuditEntry[]; };

export type DebtorRow = { id: string; customerId: string; customer: string; branch: string; overdueAmount: string; currentAmount: string; totalOpen: string; oldestBucket: string; risk: string; recommendation: string; score: number; };
export type StatementRow = { id: string; customerId: string; customer: string; branch: string; balance: string; overdueInvoices: number; lastIssued: string; nextAction: string; status: string; };
export type CashUpRow = { id: string; branch: string; date: string; expected: string; counted: string; variance: string; status: string; owner: string; recommendation: string; };
export type ExpenseRow = { id: string; branch: string; category: string; supplier: string; amount: string; status: string; submittedBy: string; incurredOn: string; recommendation: string; };
export type CreditorRow = { id: string; supplier: string; branch: string; outstanding: string; dueWindow: string; status: string; recommendation: string; };
export type FinanceExceptionRow = { id: string; kind: string; title: string; branch: string; severity: string; detail: string; action: string; recordPath: string; };
export type AccountingOverview = {
  kpis: KPI[];
  priorityActions: FinanceExceptionRow[];
  debtors: DebtorRow[];
  statements: StatementRow[];
  cashUps: CashUpRow[];
  expenses: ExpenseRow[];
  creditors: CreditorRow[];
};

export type LedgerAccountRow = { code: string; name: string; type: string; balance: string; status: string; movement: string; };
export type JournalEntryRow = { id: string; date: string; source: string; reference: string; status: string; total: string; owner: string; summary: string; };
export type LedgerPayload = { summary: KPI[]; accounts: LedgerAccountRow[]; journals: JournalEntryRow[]; trialBalanceReady: boolean; };
export type SupplierBillRow = { id: string; supplier: string; branch: string; amount: string; dueDate: string; status: string; matchStatus: string; recommendation: string; };
export type SupplierBillsPayload = { kpis: KPI[]; bills: SupplierBillRow[]; };
export type BankAccountRow = { id: string; name: string; balance: string; unreconciled: number; suggestedMatches: number; };
export type ReconciliationItemRow = { id: string; account: string; date: string; description: string; amount: string; status: string; recommendation: string; };
export type ReconciliationPayload = { bankAccounts: BankAccountRow[]; items: ReconciliationItemRow[]; };
export type VatItemRow = { id: string; label: string; value: string; detail: string; };
export type VatPayload = { period: string; outputVat: string; inputVat: string; payable: string; status: string; items: VatItemRow[]; };
export type PeriodCloseItemRow = { id: string; label: string; status: string; owner: string; detail: string; };
export type PeriodClosePayload = { readiness: string; status: string; checklist: PeriodCloseItemRow[]; };

export type ActionCenterDomain = 'Finance' | 'Procurement' | 'Inventory' | 'Operations';
export type ActionRecommendation = { id: string; domain: ActionCenterDomain | string; title: string; detail: string; reason: string; owner: string; branch: string; priority: 'critical' | 'high' | 'medium' | 'low' | string; score: number; impact: string; actionLabel: string; recordPath: string; status: string; autoReady?: boolean; };
export type ActionCenterDomainSummary = { domain: ActionCenterDomain | string; count: number; urgent: number; headline: string; impact: string; };
export type ActionCenterResponse = { generatedAt: string; topFocus: ActionRecommendation[]; quickWins: ActionRecommendation[]; recommendationFeed: ActionRecommendation[]; domainSummaries: ActionCenterDomainSummary[]; branchSnapshots: BranchSnapshot[]; auditHighlights: ActivityEntry[]; };


export type ProcurementRecommendation = {
  id: string;
  title: string;
  detail: string;
  impact: string;
  actionLabel: string;
  recordPath: string;
  priority: 'high' | 'medium' | 'low' | string;
  domain: 'reorder' | 'supplier' | 'purchase-order' | 'exception' | string;
};
export type ReorderCandidateRow = {
  id: string;
  sku: string;
  product: string;
  branch: string;
  stock: number;
  reorderAt: number;
  deficit: number;
  supplier: string;
  urgency: string;
  recommendation: string;
  score: number;
};
export type SupplierInsightRow = {
  id: string;
  supplier: string;
  category: string;
  leadTime: string;
  status: string;
  reliability: string;
  score: number;
  recommendation: string;
};
export type ProcurementPoRow = {
  id: string;
  supplier: string;
  branch: string;
  status: string;
  value: string;
  eta: string;
  buyer: string;
  recommendation: string;
  score: number;
};
export type ProcurementExceptionRow = {
  id: string;
  title: string;
  severity: string;
  branch: string;
  detail: string;
  action: string;
  recordPath: string;
};
export type ProcurementOverview = {
  kpis: KPI[];
  focus: ProcurementRecommendation[];
  reorders: ReorderCandidateRow[];
  suppliers: SupplierInsightRow[];
  purchaseOrders: ProcurementPoRow[];
  exceptions: ProcurementExceptionRow[];
};


export type InventoryRow = Product & {
  product: string;
  onHand: number;
  reserved: number;
  freeToSell: number;
  coverGap: number;
  riskBand: string;
  stockRiskScore: number;
  movementBand: string;
  movementInsight: string;
  transferOptions: { branch: string; stock: number; reorderAt: number; surplus: number; movementSummary: string }[];
  suggestedTransferUnits: number;
  buyShortfallOnly: number;
  recommendation: string;
};
export type InventoryStockRiskRow = { id: string; sku: string; product: string; branch: string; onHand: number; reserved: number; freeToSell: number; reorderAt: number; coverGap: number; riskBand: string; score: number; recommendation: string; };
export type InventoryTransferRow = { id: string; sku: string; product: string; toBranch: string; fromBranch: string; suggestedUnits: number; coverGap: number; buyShortfallOnly: number; urgency: string; score: number; recommendation: string; };
export type InventoryMovementRow = { id: string; sku: string; product: string; branch: string; movementBand: string; summary: string; insight: string; score: number; recommendation: string; };
export type InventoryExceptionRow = { id: string; title: string; severity: string; branch: string; detail: string; action: string; recordPath: string; };
export type InventoryOverview = { generatedAt: string; kpis: KPI[]; focus: ProcurementRecommendation[]; stockRisks: InventoryStockRiskRow[]; transferSuggestions: InventoryTransferRow[]; movementIntelligence: InventoryMovementRow[]; exceptions: InventoryExceptionRow[]; rows: InventoryRow[]; };
