export type RoleKey = 'admin' | 'sales' | 'finance' | 'warehouse' | 'procurement' | 'operations' | 'manager' | 'executive';
export type KPI = { label: string; value: string; detail: string };
export type PanelGroup = { title: string; items: string[] };
export type Customer = {
  id: string;
  name: string;
  owner: string;
  branch: string;
  status: string;
  balance: string;
  risk: string;
  creditTerms: string;
  priceList: string;
  contact: string;
  phone: string;
  notes: string;
  nextAction: string;
  activity: string[];
};

export type Supplier = {
  id: string;
  name: string;
  category: string;
  leadTime: string;
  status: string;
  contact: string;
  nextAction: string;
};
export type PurchaseOrder = {
  id: string;
  supplier: string;
  branch: string;
  status: string;
  value: string;
  eta: string;
  buyer: string;
  nextAction: string;
};

export type Product = {
  id: string;
  sku: string;
  name: string;
  branch: string;
  status: string;
  stock: number;
  reorderAt: number;
  price: string;
  cost: string;
  supplier: string;
  barcode: string;
  variants: string;
  movementSummary: string;
  nextAction: string;
};
export type QuoteStatus = 'Draft' | 'Pending approval' | 'Approved' | 'Sent to customer' | 'Converted';
export type Quote = { id: string; customer: string; owner: string; value: string; status: string; validity: string; branch: string; trigger: string; updated: string; notes: string; nextAction: string; };
export type QuoteLine = { id: string; sku: string; description: string; qty: number; unitPrice: string; total: string; };
export type QuoteWorkflowEvent = { label: string; detail: string; };
export type ActivityEntry = {
  id: string;
  title: string;
  detail: string;
  actor: string;
  timestamp: string;
  recordType: 'quote' | 'invoice' | 'payment' | 'system' | string;
  recordId: string;
  recordPath: string;
  customerId?: string | null;
  status?: string;
};
export type QuoteDetail = Quote & {
  customerId?: string;
  subtotal: string;
  tax: string;
  total: string;
  marginBand: string;
  approvalOwner: string;
  sourceCustomerId: string;
  lines: QuoteLine[];
  workflow: QuoteWorkflowEvent[];
  activityLog: ActivityEntry[];
};
export type Invoice = { id: string; customerId?: string; customer: string; amount: string; branch: string; status: string; due: string; source: string; paymentStatus: string; tax: string; reminders: string; nextAction: string; };
export type InvoiceDetail = Invoice & {
  sourceCustomerId: string;
  sourceQuoteId: string | null;
  subtotal: string;
  total: string;
  issuedOn: string;
  lines: QuoteLine[];
  workflow: QuoteWorkflowEvent[];
  activityLog: ActivityEntry[];
};
export type Payment = {
  id: string;
  ref: string;
  customerId: string;
  party: string;
  amount: string;
  method: string;
  status: string;
  date: string;
  appliedTo: string;
  proof: string;
  nextAction: string;
  linkedInvoiceId?: string | null;
  sourceCustomerId?: string;
  activityLog?: ActivityEntry[];
};
export type NotificationType = 'approval' | 'collection' | 'payment' | 'stock' | 'general';
export type Notification = {
  id: string;
  title: string;
  meta: string;
  state: string;
  read: boolean;
  type: NotificationType | string;
  dismissed?: boolean;
  snoozedUntil?: string | null;
};
export type AutomationSettings = {
  triggerMode: string;
  closeTime: string;
  sendToManagers: boolean;
  sendToExecutives: boolean;
  managerRecipients: string[];
  executiveRecipients: string[];
  defaultManagerBranch: string;
  branchManagers: { branch: string; manager: string; email: string }[];
};
export type Settings = {
  themes: string[];
  paymentModes: string[];
  density: string[];
  supportEmail: string;
  whatsapp: string;
  business: { currency: string; taxDefault: string; paymentTerms: string; defaultBranch: string; };
  automation?: AutomationSettings;
};
export type Role = { key: RoleKey; label: string; description: string; dashboards: string[]; };
export type TopClient = { customerId: string; name: string; revenue: string; invoices: number; averageOrderValue: string; overdueBalance: string; trend: string; };
export type OperationalActionItem = {
  id: string;
  title: string;
  detail: string;
  owner: string;
  branch: string;
  priority: 'high' | 'medium' | 'low' | string;
  recordPath: string;
  actionLabel: string;
  status: string;
};
export type BranchSnapshot = { branch: string; approvals: number; collections: number; exceptions: number };
export type DashboardResponse = {
  role: string;
  kpis: KPI[];
  panels: PanelGroup[];
  highlights: Notification[];
  recentCustomers: Customer[];
  lowStockProducts: Product[];
  topClients: TopClient[];
  actionCenter: {
    branchSnapshots: BranchSnapshot[];
    actionQueue: OperationalActionItem[];
    auditHighlights: ActivityEntry[];
  };
};
export type PurchaseHistoryEntry = {
  id: string;
  date: string;
  type: 'invoice' | 'payment' | 'quote';
  reference: string;
  amount: string;
  status: string;
  note: string;
};
export type TopProduct = { sku: string; name: string; quantity: number; revenue: string; };
export type CustomerSummary = {
  customerId: string;
  totalSpend: string;
  invoiceCount: number;
  averageOrderValue: string;
  overdueBalance: string;
  lastPurchaseDate: string;
  lastPaymentDate: string;
  collectionStatus: string;
  topProducts: TopProduct[];
  openQuotes: Quote[];
  recentInvoices: Invoice[];
  recentPayments: Payment[];
  purchaseHistory: PurchaseHistoryEntry[];
  overdueInvoices: number;
  openBalance: string;
  accountHealth: string;
  linkedActivity: ActivityEntry[];
};
export type QuoteConversionResult = {
  quote: QuoteDetail;
  invoice: InvoiceDetail;
  reused: boolean;
};
export type EmailTemplateKind = 'quote-send' | 'invoice-reminder' | 'payment-proof';
export type EmailDraft = {
  kind: EmailTemplateKind;
  subject: string;
  to: string;
  cc?: string;
  recordId: string;
  customerName: string;
  intro: string;
  body: string[];
  closing: string;
};
export type ReportBranch = {
  branchId: string;
  branch: string;
  date: string;
  totalSales: number;
  target: number;
  varianceToTarget: number;
  targetAchievedPct: number;
  posSales: number;
  invoiceSales: number;
  cashSales: number;
  cardSales: number;
  eftSales: number;
  transactions: number;
  averageBasket: number;
};
export type ReportTotals = {
  totalSales: number;
  target: number;
  varianceToTarget: number;
  targetAchievedPct: number;
  posSales: number;
  invoiceSales: number;
  cashSales: number;
  cardSales: number;
  eftSales: number;
  transactions: number;
};
export type SellerRow = { name: string; branch: string; sales: number; target: number };
export type EmailDispatch = {
  id: string;
  sentAt: string;
  recipients: string[];
  provider: string;
  subject: string;
  status: string;
  date: string;
  companyTotal: number;
  branchCount: number;
};
export type DayCloseRecord = {
  id: string;
  closedAt: string;
  trigger: string;
  date: string;
  totalSales: number;
  varianceToTarget: number;
};
export type ReportsResponse = {
  scope: string;
  date: string;
  canViewAllBranches: boolean;
  visibleBranches: ReportBranch[];
  totals: ReportTotals;
  sellerBoard: SellerRow[];
  emailPreview: { subject: string; body: string };
  emailDispatches: EmailDispatch[];
  dayCloseHistory: DayCloseRecord[];
  automation: AutomationSettings;
};
